// Generated by CoffeeScript 1.9.0
(function() {
  var AsyncPool, Promise;

  Promise = require('bluebird');

  AsyncPool = (function() {
    function AsyncPool(resources) {
      this.resources = resources;
      this.waiting = [];
    }

    AsyncPool.prototype.use = function() {
      var self;
      self = this;
      if (this.resources == null) {
        throw new Error('AsyncPool is closed.');
      }
      return new Promise(function(res) {
        var resource;
        resource = self.resources.pop();
        if (resource != null) {
          return res(resource);
        }
        return self.waiting.push(res);
      }).disposer(function(resource) {
        var waiter, _ref;
        waiter = self.waiting.pop();
        console.log('-- client returned; waiter', (_ref = waiter != null ? waiter.name : void 0) != null ? _ref : waiter);
        if (waiter != null) {
          return waiter(resource);
        } else {
          return self.resources.push(resource);
        }
      });
    };

    AsyncPool.prototype.close = function() {
      return this.resources = null;
    };

    return AsyncPool;

  })();

  module.exports = AsyncPool;

}).call(this);
