// Generated by CoffeeScript 1.9.0
(function() {
  var AsyncPool, Promise;

  Promise = require('bluebird');

  AsyncPool = (function() {
    function AsyncPool(resources) {
      this.resources = resources;
      this.waiting = [];
    }

    AsyncPool.prototype.use = function() {
      var self;
      self = this;
      return new Promise(function(res) {
        var resource;
        resource = self.resources.pop();
        if (resource != null) {
          return res(resource);
        }
        return self.waiting.push(res);
      }).disposer(function(resource) {
        var waiter;
        waiter = self.waiting.pop();
        if (waiter != null) {
          return waiter(resource);
        } else {
          return self.resources.push(resource);
        }
      });
    };

    return AsyncPool;

  })();

  module.exports = AsyncPool;

}).call(this);
